name: website
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  confetti: ^0.6.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_screenutil: 5.2.0
  google_fonts: ^2.3.1
  lottie: ^1.2.2
  mask_text_input_formatter: ^2.3.0
  responsive_framework: ^0.1.7
  rxdart: ^0.27.3
  transparent_image: ^2.0.0
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/
